### ISSUE TITLE
'MagentoTransport' object has no attribute '_connection'

### ISSUE THREAD

**Issue by csansone** [bernieke/python-magento#7]
I had been working with version `0.3.4` and upgraded to `1.0.1`. After upgrade I cannot establish a connection. 

Tried a fresh virtualenv with only this package in order to rule out any dependency issues that might exist, and got the same result.

Using `1.0.0` now and am not experiencing the issue.

```
Traceback (most recent call last):
  File "mage.py", line 9, in <module>
    mag = MagentoAPI('www.MYDOMAIN.com', 80, 'MYAPIUSER', 'MYAPIKEY', verbose=False)
  File "C:\Users\Chris\.virtualenvs\analytics1\lib\site-packages\magento\magento_api.py", line 61, in __init__
    self.login()
  File "C:\Users\Chris\.virtualenvs\analytics1\lib\site-packages\magento\magento_api.py", line 108, in login
    self._session_id = self._client.login(self._api_user, self._api_key)
  File "C:\Python27\Lib\xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\Lib\xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "C:\Python27\Lib\xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\Lib\xmlrpclib.py", line 1293, in single_request
    h = self.make_connection(host)
  File "C:\Python27\Lib\xmlrpclib.py", line 1373, in make_connection
    if self._connection and host == self._connection[0]:
```

**Comment by bernieke** [comment]
Fixed. 1.0.2 released with the fix.

Problem only existed on python2, and was due to differing behavior concerning mixins between python2 and python3.
